# Generated by Django 3.1.2 on 2021-10-15 17:16

import api.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viloyat', models.CharField(blank=True, max_length=40, null=True)),
                ('tuman', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('params', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=6, max_digits=9), null=True, size=2)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='logo')),
                ('our_history', models.TextField(blank=True, null=True)),
                ('why_us', models.TextField(blank=True, null=True)),
                ('program1', models.TextField(blank=True, null=True)),
                ('program2', models.TextField(blank=True, null=True)),
                ('program3', models.TextField(blank=True, null=True)),
                ('post_image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('post_text1', models.TextField(blank=True, null=True)),
                ('post_image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('post_text2', models.TextField(blank=True, null=True)),
                ('post_image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('post_text3', models.TextField(blank=True, null=True)),
                ('post_image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('post_text4', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerifyAccountCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=120)),
                ('code', models.CharField(default=api.models.generate_activation_code, max_length=6)),
                ('registered_time', models.DateTimeField(auto_now_add=True)),
                ('verified_time', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Verify Email Code',
                'verbose_name_plural': 'Verify Email Codes',
            },
        ),
        migrations.CreateModel(
            name='Yangilik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='')),
                ('kg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kg')),
            ],
        ),
        migrations.CreateModel(
            name='Xodim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('full_name', models.CharField(max_length=100)),
                ('lavozim', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('mutaxassislik', models.CharField(max_length=50)),
                ('otm', models.CharField(blank=True, max_length=50, null=True)),
                ('about', models.TextField()),
                ('phone', models.CharField(max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('kg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kg')),
            ],
        ),
        migrations.CreateModel(
            name='Tadbir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=100)),
                ('kg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kg')),
            ],
        ),
        migrations.CreateModel(
            name='Rahbariyat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('full_name', models.CharField(max_length=100)),
                ('lavozim', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('mutaxassislik', models.CharField(max_length=50)),
                ('otm', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('phone', models.CharField(max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('kg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kg')),
            ],
        ),
        migrations.CreateModel(
            name='Oshxona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kindergarden', to='api.kg')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('tarkib', models.TextField()),
                ('oshxona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kindergarden', to='api.oshxona')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menues',
            },
        ),
        migrations.CreateModel(
            name='Image_Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('image3', models.ImageField(upload_to='')),
                ('image4', models.ImageField(upload_to='')),
                ('image5', models.ImageField(upload_to='')),
                ('image6', models.ImageField(upload_to='')),
                ('image7', models.ImageField(upload_to='')),
                ('image8', models.ImageField(upload_to='')),
                ('kg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kg')),
            ],
        ),
    ]
