# Generated by Django 3.1.2 on 2021-09-27 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=50)),
                ('telegram', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tuman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viloyat', models.CharField(choices=[('toshkent', 'Toshkent'), ('buxoro', 'Buxoro'), ('samarqand', 'Samarqand'), ('andijon', 'Andijon'), ('xorazm', 'Xorazm'), ('navoi', 'Navoi')], max_length=100)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Yangilik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='')),
                ('kg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kg')),
            ],
        ),
        migrations.CreateModel(
            name='Xodim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='')),
                ('full_name', models.CharField(max_length=100)),
                ('lavozim', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('mutaxassislik', models.CharField(max_length=50)),
                ('otm', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=50)),
                ('kg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kg')),
            ],
        ),
        migrations.CreateModel(
            name='Tadbir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=100)),
                ('kg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kg')),
            ],
        ),
        migrations.CreateModel(
            name='Rahbariyat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='')),
                ('full_name', models.CharField(max_length=100)),
                ('lavozim', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('mutaxassislik', models.CharField(max_length=50)),
                ('otm', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=50)),
                ('kg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kg')),
            ],
        ),
        migrations.AddField(
            model_name='kg',
            name='tuman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tuman'),
        ),
        migrations.CreateModel(
            name='Image_Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('kg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kg')),
            ],
        ),
    ]
