<<<<<<< HEAD
# Generated by Django 3.1.2 on 2021-08-22 12:22
=======
# Generated by Django 3.2.6 on 2021-08-22 09:23
>>>>>>> d2cfdc0fdf128c512ab69389b436ec140963ac5f

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KG',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> d2cfdc0fdf128c512ab69389b436ec140963ac5f
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=50)),
                ('telgram', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tuman',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viloyat', models.CharField(choices=[('toshkent', 'Toshkent'), ('buxoro', 'Buxoro'), ('samarqand', 'Samarqand'), ('andijon', 'Andijon'), ('xorazm', 'Xorazm'), ('navoi', 'Navoi')], max_length=100)),
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viloyat', models.CharField(choices=[('toshkent', 'Toshkent'), ('buxoro', 'Buxoro'), ('samarqand', 'Samarqand'), ('andijon', 'Andijon'), ('xorazm', 'Xorazm'), ('navoi', 'Navoi')], max_length=50)),
>>>>>>> d2cfdc0fdf128c512ab69389b436ec140963ac5f
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Yengilik',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> d2cfdc0fdf128c512ab69389b436ec140963ac5f
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='')),
                ('kg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kg')),
            ],
        ),
        migrations.CreateModel(
            name='Tadbir',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> d2cfdc0fdf128c512ab69389b436ec140963ac5f
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=100)),
                ('kg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kg')),
            ],
        ),
        migrations.CreateModel(
            name='Rahbariyat',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> d2cfdc0fdf128c512ab69389b436ec140963ac5f
                ('rasm', models.ImageField(upload_to='')),
                ('full_name', models.CharField(max_length=100)),
                ('lovozim', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('mutaxassisli', models.CharField(max_length=50)),
                ('otm', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=50)),
                ('kg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kg')),
            ],
        ),
        migrations.AddField(
            model_name='kg',
            name='tuman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tuman'),
        ),
        migrations.CreateModel(
            name='Image_Vedio',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> d2cfdc0fdf128c512ab69389b436ec140963ac5f
                ('image', models.ImageField(upload_to='')),
                ('kg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kg')),
            ],
        ),
    ]
