# Generated by Django 3.1.2 on 2021-10-17 14:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kg',
            name='params',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=40, max_digits=50), null=True, size=2),
        ),
    ]
