# Generated by Django 3.1.2 on 2021-10-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kg',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kg',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kg',
            name='our_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kg',
            name='program1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kg',
            name='program2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kg',
            name='program3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kg',
            name='why_us',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kg',
            name='telegram',
            field=models.URLField(),
        ),
    ]
