# Generated by Django 3.1.2 on 2021-09-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210929_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kg',
            name='tuman',
            field=models.CharField(max_length=50),
        ),
    ]
