# Generated by Django 3.1.2 on 2021-10-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211017_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='kg',
            name='program1_img',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='program_images'),
        ),
        migrations.AddField(
            model_name='kg',
            name='program2_img',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='program_images'),
        ),
        migrations.AddField(
            model_name='kg',
            name='program3_img',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='program_images'),
        ),
    ]
