# Generated by Django 3.1.2 on 2021-08-24 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210824_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kg',
            old_name='telgram',
            new_name='telegram',
        ),
        migrations.RenameField(
            model_name='rahbariyat',
            old_name='lovozim',
            new_name='lavozim',
        ),
        migrations.RenameField(
            model_name='rahbariyat',
            old_name='mutaxassisli',
            new_name='mutaxassislik',
        ),
    ]
