# Generated by Django 3.1.2 on 2021-08-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210824_1900'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image_Vedio',
            new_name='Image_Video',
        ),
    ]
