# Generated by Django 3.1.2 on 2021-09-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210929_2231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tuman',
        ),
        migrations.AlterField(
            model_name='kg',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='kg',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
