# Generated by Django 3.1.2 on 2021-09-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210929_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rahbariyat',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tadbir',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='yangilik',
            name='date',
            field=models.DateField(),
        ),
    ]
