# Generated by Django 3.1.2 on 2021-10-17 14:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211017_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kg',
            name='params',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), null=True, size=2),
        ),
    ]
