# Generated by Django 3.1.2 on 2021-10-17 14:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211017_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kg',
            name='params',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True), null=True, size=2),
        ),
    ]
