# Generated by Django 3.1.2 on 2021-09-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210930_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rahbariyat',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='otm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
