# Generated by Django 3.1.2 on 2021-10-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211012_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_video',
            name='video',
        ),
    ]
