# Generated by Django 3.1.2 on 2021-10-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211017_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kg',
            name='program1_img',
            field=models.ImageField(blank=True, null=True, upload_to='program_images'),
        ),
        migrations.AlterField(
            model_name='kg',
            name='program2_img',
            field=models.ImageField(blank=True, null=True, upload_to='program_images'),
        ),
        migrations.AlterField(
            model_name='kg',
            name='program3_img',
            field=models.ImageField(blank=True, null=True, upload_to='program_images'),
        ),
    ]
