# Generated by Django 3.1.2 on 2021-10-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211017_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kg',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
    ]
